### ISSUE TITLE
[CCA-Diversity] Move back to webpack CLI

### ISSUE THREAD

**Issue by jvanbruegge** [cyclejs-community/create-cycle-app#107]
The custom webpack dev server does not emit typescript checking errors. 
And the build script aborts the compilation if there is a type checking error. Normally typescript would emit, even if there is a mistake

**Comment by jvanbruegge** [comment]
Plus this would not leave traces on eject

**Comment by jvanbruegge** [comment]
we might have to create a plugin for stuff like build size reporting

**Comment by nickbalestra** [comment]
See Discussion in #108
