### ISSUE TITLE
Investigate possible use of yarn instead npm, when present

### ISSUE THREAD

**Issue by geovanisouza92** [cyclejs-community/create-cycle-app#11]

**Comment by geovanisouza92** [comment]
I've made some tests with yarn under yarnify branch, but due to https://github.com/yarnpkg/yarn/issues/760 and https://github.com/yarnpkg/yarn/issues/620, among other issues, this is not yet a seamless change.

For now, we must wait, at least the cited issues be solved.

Anyone reading this, feel free to try further and make a PR. :)

**Comment by nickbalestra** [comment]
Nice, thanks for the update.

**Comment by geovanisouza92** [comment]
Both issues are closed now. It seems that still needs a new release from yarn, but I'll check this again asap.
