### ISSUE TITLE
Publish new version of create-cycle-app

### ISSUE THREAD

**Issue by jvanbruegge** [cyclejs-community/create-cycle-app#115]
To deliver an important fix with package names and the option to use yarn.

@nickbalestra or optional give access rights on npm

**Comment by jvanbruegge** [comment]
@geovanisouza92 I think you also could publish a new version.
Sadly I cant develop locally without yarn because of npm bugs

**Comment by nickbalestra** [comment]
https://www.npmjs.com/package/create-cycle-app done, sorry for the belated answer
