### ISSUE TITLE
Duplicate versions of xstream

### ISSUE THREAD

**Issue by geovanisouza92** [cyclejs-community/create-cycle-app#117]
**Code to reproduce the issue:**

    create-cycle-app example --flavor cycle-scripts-one-fits-all
    cd example
    npm run eject
    npm install --save-dev webpack-bundle-analyzer

Change webpack.config.js as the following;

```javascript
const BundleAnalyzerPlugin = require('webpack-bundle-analyzer').BundleAnalyzerPlugin;

module.exports = {
    // ...
    plugins: [new BundleAnalyzerPlugin()]
};
```

    npm run build

**Expected behavior:**

Include `xstream` on the bundle only once (the blue rect)

**Actual behavior:**

Included **four** times on the bundle

![selecao_007](https://user-images.githubusercontent.com/786105/31187120-3842c206-a907-11e7-9721-99df47690c65.png)

**Versions of packages used:**

- create-cycle-app@3.0.8
- cycle-scripts-one-fits-all@4.2.2

```
yarn list v0.27.5
├─ @cycle/dom@18.3.0
├─ @cycle/http@14.4.0
├─ @cycle/isolate@3.1.0
├─ @cycle/run@3.3.0
├─ @cycle/time@0.8.0
├─ cycle-onionify@3.3.0
├─ cycle-restart@0.2.2
├─ xstream@10.9.0
```

---

This is related to `@cycle/run`, `@cycle/time` and `cycle-onionify`, spotted on https://github.com/cyclejs/cyclejs/issues/700

**Comment by jvanbruegge** [comment]
Will investigate tomorrow
Together with this uglify bug

**Comment by jvanbruegge** [comment]
Not the case any more in one-fits-all V5
