### ISSUE TITLE
port 8000 is not documented

### ISSUE THREAD

**Issue by cloud-walker** [cyclejs-community/create-cycle-app#12]
The development server that start on `npm start` will listen on port **8000** but is not documented anywhere.

**Comment by geovanisouza92** [comment]
Good point, I'll take care of this. Thank you for reporting.

**Comment by cloud-walker** [comment]
I'm happy to help, but for now I'm not too confident with the package

**Comment by geovanisouza92** [comment]
@cloud-walker You are already helping :)

You could take a look on other issues and provide your thoughts.

Feel free to open more issues and PRs.
