### ISSUE TITLE
Duplicate meta tags for favicon

### ISSUE THREAD

**Issue by jikkai** [cyclejs-community/create-cycle-app#121]
**Code to reproduce the issue:**
```
create-cycle-app demo
cd demo
npm i
npm run build
```

**Expected behavior:**

Only one meta tag for favicon in complied html.

**Actual behavior:**

[/public/index.html#L6](https://github.com/cyclejs-community/create-cycle-app/blob/7b7ab8a03e103bacce4672477d0261094e81f3af/packages/cycle-scripts/template/public/index.html#L6)

[/public/index.html#L93](https://github.com/cyclejs-community/create-cycle-app/blob/7b7ab8a03e103bacce4672477d0261094e81f3af/packages/cycle-scripts/configs/javascript/webpack.config.dev.js#L93)

Accoding to this two files, there will be two duplicate favicon in complied html.

output html:

```
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" type="image/png" href="favicon.png" />
    <title>Cycle App</title>
  <link rel="shortcut icon" href="favicon.png"></head>
```

**Versions of packages used:**

create-cycle-app@4.0.0

**Comment by olpeh** [comment]
Tried looking into the issue, but was unable to reproduce the duplicate favicon meta tag.

**Comment by jvanbruegge** [comment]
Most likely due to an old version of the template, thanks for looking into it
