### ISSUE TITLE
npm run test fails on v4.0.0

### ISSUE THREAD

**Issue by mictian** [cyclejs-community/create-cycle-app#122]
**Code to reproduce the issue:**
`npm run test`

**Expected behavior:**
Tests to run

**Actual behavior:**

> Enabling watch mode
events.js:167
      throw er; // Unhandled 'error' event
      ^
> 
> Error: spawn /home/mictian/tmp/cycleAppTest/node_modules/.bin/mocha ENOENT
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:217:19)
>     at onErrorNT (internal/child_process.js:394:16)
>     at process._tickCallback (internal/process/next_tick.js:174:19)
>     at Function.Module.runMain (internal/modules/cjs/loader.js:721:11)
>     at startup (internal/bootstrap/node.js:228:19)
>     at bootstrapNodeJSCore (internal/bootstrap/node.js:575:3)
> Emitted 'error' event at:
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:223:12)
>     at onErrorNT (internal/child_process.js:394:16)
>     [... lines matching original stack trace ...]
>     at bootstrapNodeJSCore (internal/bootstrap/node.js:575:3)

**Versions of packages used:**
4.0.0

**Remarks:**
If you see the test script (file: [test.js](https://github.com/cyclejs-community/create-cycle-app/blob/master/packages/cycle-scripts/scripts/test.js) ) clearly the code was done with `mocha` in mind.
However, among the dependencies the only test runner installed is `jest`  (https://github.com/cyclejs-community/create-cycle-app/blob/master/packages/cycle-scripts/package.json#L43).

What is the expected test runner?
What should be fixed? The test script or the dependencies?

Thanks in advance,
Mictian

**Comment by jvanbruegge** [comment]
The flavor that comes with create-cycle-app is not really maintained any more. I will replace it with my own `one-fits-all` flavor soon. You could use that instead.

**Comment by mictian** [comment]
Thank you for your super fast replay :+1:  Got it.
In that case this issue does not have sense.
