### ISSUE TITLE
New flavor

### ISSUE THREAD

**Issue by Widdershin** [cyclejs-community/create-cycle-app#16]
Hi! Just opening an issue to say that I've created a new flavor:

https://github.com/Widdershin/cycle-scripts-widdershin

It's based off of es-browserify, but has an eslint config for semicolons, a separate test directory, includes babel-plugin-transform-object-rest-spread and a few more things.

If you like, I would love to have it on the list in the README.

Thanks!

**Comment by geovanisouza92** [comment]
Really nice @Widdershin !

Feel free to make a PR for the README.

We are discussing a better way to handle the discovery in #8, eliminating the current gist. Feel free to share your thoughts there. :)

**Comment by nickbalestra** [comment]
Noice @Widdershin !!!
@geovanisouza92 I'll try to put sometime for this(#8) together tomorrow evening so that we can roll it out.

**Comment by nickbalestra** [comment]
@Widdershin your flavor is in! 
To give it a spin, just update create-cycle-app and run it, select `discover more...` under the flavor options and you will see that a `Widdershin` flavor will be available (it will be pulled and installed from your repo).
 
I didn't know how to properly name it, so if you feel, free to change it in something more meaningful for others [here](https://github.com/cyclejs-community/create-cycle-app/blob/master/create-cycle-app/communityFlavors.json#L3). 

Thanks again for it!
