### ISSUE TITLE
Flavor discover method

### ISSUE THREAD

**Issue by nickbalestra** [cyclejs-community/create-cycle-app#2]
I think that at some point we should aim to bring the flavor-discovery mechanism within the create-cycle-app scope and not dependent on external gists? Would make it easier to maintain.

Any thoughts?

**Comment by geovanisouza92** [comment]
I think it's a nice idea. I just used a gist for sake of simplicity, but having aother mechanism, like tracking keywords on npm or having a real registry it's event better.

**Comment by nickbalestra** [comment]
I was thinking about tracking keywords on npm as well, but to start with I will probably simply limit discovery to the ones that come bundled with the app, the basic ones. 

For the others we could track npm keyboard and mantain an updated list of the ones availables on the readme, with a generic instruction on how to use those as well. (Later on we could add a step explicitly asking the user if he want to go with the bundled ones or discover what flavor are available on npm...)

The rationale for this is to keep the 'training-wheels' experience as KISS as possible (don't make me think, kinda of experience) while still allowing to go with more advanced flavors.
