### ISSUE TITLE
Continuos integration

### ISSUE THREAD

**Issue by nickbalestra** [cyclejs-community/create-cycle-app#3]
We could perhapsh hook in travis or similar, so that we run at least the test against each PR, what you are your toughts in this direction?

**Comment by geovanisouza92** [comment]
I think that travis is a good choice.

- For the `start` script could be just e2e test to check if the app is rendering as expected without errors
- For `test` if it runs without error code
- For `build`  if it runs without error code and produces the expected files
- For `take-off-training-wheels` if it updates the `package.json` and place scripts correctly

**Comment by nickbalestra** [comment]
Make sense indeed.

Sounds like a plan to me. 
I'll look into adding this next week

**Comment by nickbalestra** [comment]
So I was thinking a bit more and i guess that each flavor should come with some test, namely to check that the following runs correctly `for each streamLib option`:

- [ ] init -> it generate file structure and files correctly
- [ ] start -> e2e test to check if the app is rendering as expected
- [ ] test -> runs without error code
- [ ] build -> produces the expected files
- [ ] take-off-training-wheels -> updates the package.json and place scripts correctly

@geovanisouza92 @Widdershin anything I'm missing or you think we should take into consideration? I think that should be enough to get us starting

**Comment by geovanisouza92** [comment]
I'm experimenting with this under `automated-tests` branch

**Comment by geovanisouza92** [comment]
Progress: Overall tests are placed, still missing some specific flavor's checking. E2E tests with Zombie.js fails oddly (ok, fail, ok, fail, ok, fail) (suspects include budo and browserify latency).

**Comment by nickbalestra** [comment]
Awesome. I'll give it a go tomorrow, and try to investigate issues

**Comment by geovanisouza92** [comment]
Note to self: move tests to root folder
