### ISSUE TITLE
Limit stream library support within a custom flavor

### ISSUE THREAD

**Issue by nickbalestra** [cyclejs-community/create-cycle-app#33]
Custom flavors should be able to inform about the supported stream libs, opting out from the stream library selection in case only 1 is supported.

**Comment by nickbalestra** [comment]
@geovanisouza92  @Widdershin I've been thinking about this... 

tl;rd: imho custom flavors should come full battery included (no options for the end uses to mix them with a stream library of their choice)

Rationale: 3rd part flavors (no core-flavors) shouldn't be able to hook into the `streamLibQuestion` at all. Being able to mix and match stream libraries make sense at a core-flavor level but not for others, as it will result instead in more overhead for flavors maintainers (dependencies, documentation,..). Non core flavors should be opinionated in this regard.

My proposal then is to simply remove this option for custom flavors, so you pick the flavor you want, and if it ain't a core flavor it will just install as is. What you think?

**Comment by Widdershin** [comment]
That totally works for my usecase. Maybe we could do that in the short term, and if anyone in future wants to support multiple stream libraries in a custom flavor we could revisit it.

**Comment by nickbalestra** [comment]
Totally reasonable, me likes that plan!
I'll try to get this out of the door in the upcoming days.
