### ISSUE TITLE
Rethinking scripts post take-off-training-wheels

### ISSUE THREAD

**Issue by nickbalestra** [cyclejs-community/create-cycle-app#4]
While working ont he es6-webpack flavour I noticed that would be nice to be able to have a cleaner post `take-off-training-wheels.js` version of the scripts. 

At the moment we simply move them in the .scripts folder and we reference them wihin the package.json scripts field. 

Some of them could be simply rewritten as cli cmds within the npm script, together with some files being created whenever needed (i.e: .babelrc and webpack.config.js). 

Once we have all the 4 basics flavours in place we can perhaps start thinking on how to improve this part of the experience.

**Comment by geovanisouza92** [comment]
Yeah, this is something that I thought while working at the first flavor. As I took `create-react-app` as reference, and it only have a single bloated `react-scripts`, this is something that I leave to be addressed later.

Each flavor is completely independent, and could evolve freely, so, while maintaining the same contract with other flavors, each script could do what is more suitable for each case.

So, writing configuration files and using npm scripts more extensively, which is something the user that uses `take-off-training-wheels` probably will do, is not only OK, but desirable in some cases. The idea is that `take-off-training-wheels` give all the power (and responsibility) to the user.

**Comment by nickbalestra** [comment]
Totally agree.
On a side note, I see we don't have any labels for issues, perhaps we want to add just a couple of labels for basic things, like `nice to have`, `bug`, `discussion`, ... ?

**Comment by geovanisouza92** [comment]
Yeah, I just added the default labels, but I'm thinking if makes sense to create more, like @staltz did on cyclejs monorepo... That is a bigger project, with lot contributions caming from everywere, so, I think that was a must.

**Comment by nickbalestra** [comment]
Nice job with labels, me likes it 💯 !
#19 and #15 address this issue in regards to how we handle `.babelrc` config files. 

TODO: make sure webpack based flavors also properly generates:
- [ ] webpack.config.js 
- [ ] webpack.production.config.js

**Comment by jvanbruegge** [comment]
I did this here: https://github.com/cyclejs-community/create-cycle-app-flavors/blob/master/packages/cycle-scripts-one-fits-all/scripts/eject.js
eject does not leave any traces
