### ISSUE TITLE
streamLib

### ISSUE THREAD

**Issue by nickbalestra** [cyclejs-community/create-cycle-app#40]
I noticed that now that we don't have the streamLib choosing step anymore for non-core flavors, we cannot use the core flavors with the --flavor flag.

@geovanisouza92 , although maybe this is a non-issue it made me think that perhaps flavors should be the ones specifying if a streamLib choosing step is needed (if streamLibs supported > 1). What will you suggest?

**Comment by geovanisouza92** [comment]
I agree. We just need to find the API change to make them work seamlessly.

**Comment by geovanisouza92** [comment]
Just noticed that removing the option for streamLib on command line make hard to test manually the flavors... :/

**Comment by nickbalestra** [comment]
I know, thats what we should fix this, and really add testing
