### ISSUE TITLE
TypeScript flavours giving error on npm start

### ISSUE THREAD

**Issue by ajmchambers** [cyclejs-community/create-cycle-app#41]
**Code to reproduce the issue:**

Ok so did some more testing:
On mac, with the same node and npm version it works fine. However when in windows (10) it gives the TypeScript error.

```
npm install -g create-cycle-app
create-cycle-app test-typescript
```

Select Typescript + Browserify and Xstream

```
cd test-typescript
npm start
``` 

**Expected behavior:**

Should start normally.

**Actual behavior:**

Getting Typescript error: 

```
TypeScript error: node_modules/@cycle/dom/lib/isolateModule.d.ts(6,35): Error TS2304: Cannot find name 'Map'.
```

**Versions of packages used:**

- node v6.9.0
- npm 3.10.8

**Comment by ajmchambers** [comment]
Not sure why, but adding: `"typeRoots" : ["./node_modules/@types"]` into the `tsconfig.json`'s `"compilerOptions"` makes it work.

**Comment by ajmchambers** [comment]
Some more testing: 
The webpack flavour is working fine actually (could have sworn it didn't work for me but its working with a fresh attempt - I may have picked the wrong option or something).

So it may be an issue with the browserify `tsify` package, this issue seems relevant:
https://github.com/TypeStrong/tsify/issues/208

**Comment by geovanisouza92** [comment]
@ajmchambers could you confirm which typescript version are you using?

**Comment by ajmchambers** [comment]
```
λ npm ls --depth=0
test-typescript@0.1.0 C:\Development\test-typescript
+-- @cycle/dom@14.0.0
+-- @cycle/xstream-run@3.1.0
+-- @types/core-js@0.9.34
+-- @types/mocha@2.2.33
+-- @types/node@6.0.47
+-- browserify@13.1.1
+-- budo@9.2.1
+-- chalk@1.1.3
+-- cross-spawn@4.0.2
+-- cycle-scripts-ts-browserify@0.1.1 extraneous
+-- dotenv@2.0.0
+-- envify@3.4.1
+-- exorcist@0.4.0
+-- fs-extra@0.30.0
+-- glob@7.1.1
+-- mocha@3.1.2
+-- tsify@2.0.2
+-- typescript@2.0.3
+-- uglifyify@3.0.4
`-- xstream@7.0.0

npm ERR! extraneous: cycle-scripts-ts-browserify@0.1.1 C:\Development\test-typescript\node_modules\cycle-scripts-ts-browserify
```

I still think it's a bug with `tsify`. 

I've been running through the debugger in vscode comparing the browserify version against the webpack version and have noticed some differences.

![comparison](https://cloud.githubusercontent.com/assets/5426717/20285985/9d013d48-aabc-11e6-9ff8-5e761beb9ba6.png)

The browserify version in the left has:
`fileName:"node_modules/@cycle/dom/lib/isolateModule.d.ts"`

And the webpack version on the right (which is working) has:
`fileName:"c:/Development/test-typescript-webpack/node_modules/@cycle/dom/lib/isolateModule.d.ts"`

Anyway thats what I've figured out so far, gonna keep poking about to see where the fileName is being set incorrectly.

**Comment by ajmchambers** [comment]
(just some more notes)

Comparing `rootFiles` in mac (left) against windows (right):

![rootnamescomparison](https://cloud.githubusercontent.com/assets/5426717/20286813/add026bc-aac0-11e6-96b8-5c8ce6b16e39.png)

For some reason the windows side is missing the 3 `@types` for core-js, mocha, and node.

**Comment by ajmchambers** [comment]
This has been fixed for me with tsify 2.0.3, closing this issue.

**Comment by geovanisouza92** [comment]
Good to hear, @ajmchambers! Please, report any other issues you found in the future.

**Comment by ajmchambers** [comment]
Cheers, will do. (and btw thanks for making this tool, love it)
