### ISSUE TITLE
test directory is in .gitignore

### ISSUE THREAD

**Issue by Widdershin** [cyclejs-community/create-cycle-app#42]
For the browserify templates, both of them have the `test` directory present in the `.gitignore`.

This seems incorrect to me, as users will write tests that won't be committed. This is also silent, so easy to not notice.

Was there a reason or shall we just fix it?

**Comment by nickbalestra** [comment]
@Widdershin I think this shouldn't be there indeed. Thanks a lot for reporting it!

**Comment by geovanisouza92** [comment]
Thanks for both!

I have no idea why I put that in first place :joy:
