### ISSUE TITLE
Replace northbrook

### ISSUE THREAD

**Issue by geovanisouza92** [cyclejs-community/create-cycle-app#44]
There are some bugs with northbrook, like:

- Sometimes it doesn't detect changes made on a single package, because it just look for changes from the latest tag, instead of "latest tag for package X"
- If you type the wrong password on `npm release`, causing an error, it assumes that the release was made (it should be transactional)

Some options are:

- Lerna
- Raw scripts

**Comment by nickbalestra** [comment]
Can I close this @geovanisouza92 ?

**Comment by geovanisouza92** [comment]
I think that we could close when #52 was confirmed as a solution for the problems that we have currently

**Comment by TylorS** [comment]
First off, if you want to replace northbrook for something else, I'm not offended :)

> Sometimes it doesn't detect changes made on a single package

Northbrook uses git commit messages to manage when to do releases. So if commit message lack certain information, it can not handle your releases correctly. This is why `northbrook commit` exists. For v4 the required parts of a commit are

```
type(<scope>): <subject>

AFFECTS: name_of_packages, separated_by, commas
```

This format is sort of a "de facto" standard originally introduced (to my knowledge) by Angular, you can see much more info [here](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-guidelines). 

The `AFFECTS` is northbrook specific, and tells northbrook which packages have changed do to a commit.

I'm not too too fond of (ab)using git commit messages like this, but I've yet to find another way that is reliable. All other alternatives I've investigated use the same kind of patterns.

--

> If you type the wrong password on npm release, causing an error, it assumes that the release was made (it should be transactional)

Unfortunately at this time v4 is not transactional during releases. I've yet to actually figure out what transactional means in all of the possible scenarios of failure that can occur during release. However, the only aspect of `northbrook release` that requires human input is `npm login`, and in the latest versions northbrook (4.4.4+) will allow retrying the log in process up to 3 times if it fails which should mitigate many mistakes that can happen.

**Comment by nickbalestra** [comment]
Thanks @TylorS !
I tried using lerna as an alternative on the v3 branch and it works pretty smoothly. I'll want to work more with both in order to see which path to go.
