### ISSUE TITLE
Webpack build fails with Typescript 2.1

### ISSUE THREAD

**Issue by wmaurer** [cyclejs-community/create-cycle-app#49]
**Code to reproduce the issue:**
$ `create-cycle-app my-app` with `TypeScript + Webpack`
$ `npm i typescript --save-dev` (installs typescript 2.1)
$ `npm start`

**Expected behavior:**
No errors ;-)

**Actual behavior:**
Error message with partial trace:
```
PS D:\Projects\my-app> npm start

> my-app@0.1.0 start D:\Projects\my-app
> cycle-scripts start

  build [========            ] 40%TypeError: Cannot read property 'exclude' of undefined
    at applyDefaults (D:\Projects\my-app\node_modules\awesome-typescript-loader\src\instance.ts:266:72)
```

**Versions of packages used:**
create-cycle-app 1.0.0
typescript 2.1

I can confirm that this does not occur with typescript 2.0.10.

**Comment by wmaurer** [comment]
Ok, I've found a solution to this problem in case anybody else comes across it. `awesome-typescript-loader` needs to be upgraded to a version that supports `typescript 2.1`.

At the time of writing, the latest version is `awesome-typescript-loader@3.0.0-beta.10`

ref: https://github.com/s-panferov/awesome-typescript-loader/issues/190

**Comment by geovanisouza92** [comment]
@nickbalestra can you take a look at this and update that dependency? :)

**Comment by nickbalestra** [comment]
Thanks @wmaurer for reporting this!
@geovanisouza92 sure! Just an idea: but maybe is worth considering to add greenkeeper?

**Comment by geovanisouza92** [comment]
Ok, let's open another issue as an enhancement.

Em seg, 12 de dez de 2016 08:31, Nick Balestra <notifications@github.com>
escreveu:
