### ISSUE TITLE
Greenkeeper

### ISSUE THREAD

**Issue by nickbalestra** [cyclejs-community/create-cycle-app#50]
Integrate [greenkeeper](https://greenkeeper.io/) for helping with keeping dependencies up to date

**Comment by Widdershin** [comment]
Let me know if you need me to enable greenkeeper at an organizational level.

**Comment by nickbalestra** [comment]
Sure thing @Widdershin, thanks!

**Comment by Widdershin** [comment]
I've enabled greenkeeper for this repository, hopefully it starts working.

If anyone else sees this and would like greenkeeper enabled, let me know. I do have the option to enable it for all repos, but I think I'll do it on request for the moment.

**Comment by nickbalestra** [comment]
Thank you so much @Widdershin, I'll digg it in the following days. 

Perhaps you want to post your message also [here](https://github.com/cyclejs-community/cyclejs-community/issues) ?

**Comment by geovanisouza92** [comment]
Let's keep this open until confirm that greenkeeper is working as intended :)

**Comment by nickbalestra** [comment]
closing this as everything seems to work 💯
