### ISSUE TITLE
Cursor navigation not working with MYSYS shell

### ISSUE THREAD

**Issue by SteveALee** [cyclejs-community/create-cycle-app#53]
**Code to reproduce the issue:**
when running
```create-cycle-app my-awesome-cycle-app```
in WIndows Msys bash shell that comes with GitHub Desktop App (atually Msys from MinGW that comes with Git for Windows) the arrow keys and color do not work 

**Expected behavior:**
Arrow keys work and highlight colour

**Actual behavior:**
No colour and arrow keys do not function

**Versions of packages used:**

Latest

This is really very low priority as running a ```Cmd``` in the default Win10 terminal is fine. I'm just recording so you have a recrd. No doubt other combinations of temrinal / shell will also fail,

**Comment by geovanisouza92** [comment]
@SteveALee This seems to be an odd behavior, with really low priority. Considering that we use sboudrias/Inquirer.js for that part of the cli, I think that you could find more answers/workarounds there.
