### ISSUE TITLE
Is the formatCodeOptions section in tsconfig.json valid?

### ISSUE THREAD

**Issue by SteveALee** [cyclejs-community/create-cycle-app#54]
The tsconfig.json contains a ```formatCodeOptions```
https://github.com/cyclejs-community/create-cycle-app/blob/master/cycle-scripts-ts-webpack/template/tsconfig.json#L13-L16

But that is not in the offical TS docs or schema? 
https://www.typescriptlang.org/docs/handbook/tsconfig-json.html
http://json.schemastore.org/tsconfig

It seems therefore to be invalid.

FYI I noticed this as Visual Studio Code didn't provide any intellisense for the secction.

**Comment by SteveALee** [comment]
These days [EditorConfig](http://editorconfig.org/) is widely supported and might be a better option if the intention is to contriol editors formatting.

**Comment by nickbalestra** [comment]
I agree with @SteveALee on the `formatCodeOptions` being part of an editorConfig instead, any reason why you added it there initially @geovanisouza92 ?

**Comment by SteveALee** [comment]
Looking around the few TS examples for cycle they often have it. My guess is it got put there by a tool in an old example and then was copied.

**Comment by geovanisouza92** [comment]
Probably I copied from cyclejs examples...

+1 for Editor Config
