### ISSUE TITLE
How about an example for a component or driver?

### ISSUE THREAD

**Issue by SteveALee** [cyclejs-community/create-cycle-app#57]
I've just been exploring how to create and publish a driver / component as a module. I want to use typescript but enable the usual commons/ES6 import options form JavaScript but expose typings for TS use and intellisense in tools like VS Code. I don't think they would ever need to be uses as global scripts so AMD no needed.

This appears to be a non trivial config and rummaging around the cycles code is making my head spin as I'm new to TS.

So this seems like a perfect candidate flavour! :) 

Anyone fancy it?

**Comment by SteveALee** [comment]
Just thought that this is **create-cycle-app** but as cycle is fractal and a component can be an app it's not a totally stupid suggestion :)

Drivers don't really fit though but I prefer one tool an not an extra **create-cycle-driver**

**Comment by SteveALee** [comment]
For reference This is a good general example I found on the topic of TS libraries with webpack

https://github.com/adrianhall/example-typescript-webpack
https://shellmonger.com/2016/03/11/creating-javascript-libraries-with-typescript-and-webpack/

I could have a go at making it a flavour

**Comment by nickbalestra** [comment]
@SteveALee cool!  We do support flavor [discovery](https://github.com/cyclejs-community/create-cycle-app#discovering-published-flavors): https://github.com/cyclejs-community/create-cycle-app#publish. Feel free to go ahead and open a PR once you have your flavor published adding it to the example list in the [docs](https://github.com/cyclejs-community/create-cycle-app#example)

Let me know if I can help anyhow

**Comment by SteveALee** [comment]
Ok but it will be a little while. I'll close this issue to avoid clutter

**Comment by nickbalestra** [comment]
Sure, no rush, feel free to open another issue in this regard whenever you feel :)
