### ISSUE TITLE
Rethinking CCA

### ISSUE THREAD

**Issue by nickbalestra** [cyclejs-community/create-cycle-app#60]
@Widdershin @geovanisouza92 @TylorS 

I think we should somehow rethink some parts of create cycle app. I'm referring to core flavors. 
Imho we try to accomodate to many options, and I think that if the aim of create-cycle-app is allowing people to get up and start quickly with cycle then it shouldn't make the user think about which xlib to use, which bundle/language ecc.. but simply kickstart him. Everything else, like special cases, configuration, ecc could be done with seperated flavors, as that is what are for.

While it seemed a nice idea when we began, Its way harder to mantain as we move along, it is also harder to add features, tests ecc, as if you add something for one core flavor the same should be applied to all as someone expect core-flavors to offer the same functionalities. 
I would suggest that we move toward a single core-flavor, no streamLib options.

- I would go with a es flavor (no ts, as this add complexity for people starting with cycle as a js fw imho), in this direction webpack-es6 could be a nice candidate to start.
- It should have CSS, proper tests and module-loading properly done, it should be good enough for people to use it in production.
- we should maintain and keep the core flavor supported as much as possible, create-react-app is a terrific example of how we should do it and try to push forward with it.

This are just some of my initial thoughts on the matter, would love to hear what you think in this direction...

**Comment by geovanisouza92** [comment]
Besides all the issues and criticism that people raise against the initial approach, I doesn't have any problems with it, but, as I've used it too little recently, I may be blind to what community expect/find with the current tool.

Considering that cyclejs/cyclejs#425 could came to life any time, what could simplify all the project, CCA can also benefit from it.

So, I would love to head what anyone think that should be the next steps.

**Comment by nickbalestra** [comment]
Created a v3 branch with relative WIP PR #63  to track progress of this

**Comment by nickbalestra** [comment]
addressed with #63
