### ISSUE TITLE
Should throw an error if --flavor is not found (instead of installing the core one)

### ISSUE THREAD

**Issue by nickbalestra** [cyclejs-community/create-cycle-app#78]
**Code to reproduce the issue:**
See https://github.com/cyclejs-community/create-cycle-app-flavors/pull/1#discussion_r99496449

**Actual behaviour:**
If an error is passed to the --flavor flag (ie not valid path to local, or not publised flavor,...) it silently install the core-flavor instead.

**Expected behaviour:**
Should throw and error

**Versions of packages used:**
create-cycle-app 3.0.5

**Comment by jvanbruegge** [comment]
I have to add that my mistake was writing `--flavour` so it should error too if use and option that is not supported

**Comment by nickbalestra** [comment]
perhaps we should support english 🇬🇧 aliases ?

**Comment by jvanbruegge** [comment]
I dont think it is needed, just notify that there is a typo :)
