### ISSUE TITLE
[CCA-Diversity] Bring typescript src into core-flavor

### ISSUE THREAD

**Issue by nickbalestra** [cyclejs-community/create-cycle-app#92]
Once https://github.com/cyclejs-community/create-cycle-app/pull/91 got merged

**Comment by jvanbruegge** [comment]
@nickbalestra I dont think the replacements work language agnostic, for typescript I would have to add quite a few
I will move the `replacements.js` to the template folder and create a new one for typescript

**Comment by nickbalestra** [comment]
Yes, maybe we could also think of better name, but agree that those should be within the `template/src/<language>`
